routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('sampah', 'SampahController');
Route::get('sampah/sortbyname','SampahController@sortByName');

app/Sampah.php
<?php

namespace App;

use Kyslik\ColumnSortable\Sortable;
use Illuminate\Database\Eloquent\Model;

class Sampah extends Model
{

    use Sortable;
    protected $table = 'sampah';

    protected $fillable = [
        'nama','kategori'
    ];

    public $sortable = ['id','nama','kategori'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/API/ResponseFormatter.php
<?php

namespace App\Http\Controllers\API;

class ResponseFormatter
{
    protected static $response = [
        'meta' => [
            'code' => 200,
            'status' => 'success',
            'message' => null
        ],
        'data' => null
    ];


    public static function success($data = null, $message = null)
    {
        self::$response['meta']['message'] = $message;
        self::$response['data'] = $data;

        return response()->json(self::$response, self::$response['meta']['code']);
    }

    public static function error($data = null, $message = null, $code = 400)
    {
        self::$response['meta']['status'] = 'error';
        self::$response['meta']['code'] = $code;
        self::$response['meta']['message'] = $message;
        self::$response['data'] = $data;

        return response()->json(self::$response, self::$response['meta']['code']);
    }


}

app/Http/Controllers/API/SampahController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Sampah;

class SampahController extends Controller
{

    
    public function all(Request $request)
    {
        $id = $request->input('id');
        $limit = $request->input('limit',10);
        $nama = $request->input('nama');
        $kategori = $request->input('kategori');


        if($id)
        {
            $sampah = Sampah::find($id);

            if ($sampah)
                return ResponseFormatter::success($sampah,'Data berhasil diambil');
            else
                return ResponseFormatter::error(null, 'Data tidak ada','404');
        }

        

        if($nama)
        {
            $sampah = Sampah::where('nama','like','%'.$nama.'%')->get();
            
            if ($sampah)
                return ResponseFormatter::success($sampah,'Data berhasil diambil');
            else
                return ResponseFormatter::error(null, 'Data tidak ada','404');
        }    

        if($kategori)
        {
            $sampah = Sampah::where('kategori','like','%'.$kategori.'%')->get();
            
            if ($sampah)
                return ResponseFormatter::success($sampah,'Data berhasil diambil');
            else
                return ResponseFormatter::error(null, 'Data tidak ada','404');
        }
        
        
        $sampah = Sampah::paginate($limit);

        return ResponseFormatter::success(
            $sampah,'Data sampah berhasil diambil'
        );
    }


    public function store(Request $request)
    {

        $validated = $request->validate([
            'nama' => 'required|max:255',
            'kategori' => 'required|string|in:Logam,Kertas,Plastik',
        ]);

        $sampah = Sampah::create ([
            'nama' => $validated['nama'],
            'kategori' => $validated['kategori'],
        ]);

       return ResponseFormatter::success($sampah, 'Data berhasil dimasukkan');
    }

    public function destroy($id)
    {
        $sampah = Sampah::destroy($id);

        if ($sampah)
            return ResponseFormatter::success($sampah,'Data berhasil dihapus');
        else
            return ResponseFormatter::error(null, 'Data tidak ada','404');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SampahController.php
<?php

namespace App\Http\Controllers;
use App\Sampah;
use Illuminate\Http\Request;

class SampahController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->has('carinama')) {
            $sampah = Sampah::where('nama','LIKE','%'.$request->carinama.'%')->paginate(10);    
        } elseif ($request->has('carikategori')) {
            $sampah = Sampah::where('kategori','LIKE','%'.$request->carikategori.'%')->paginate(10);
        }
        else {
            $sampah = Sampah::sortable()->paginate(10);
        }

        return view('home', [
            'sampah' => $sampah
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'nama' => 'required|max:255',
            'kategori' => 'required|string|in:Logam,Kertas,Plastik',
        ]);

        $sampah = Sampah::create ([
            'nama' => $validated['nama'],
            'kategori' => $validated['kategori'],
        ]);

        return redirect()->route('sampah.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sampah = Sampah::destroy($id);

        return redirect()->back();
    }

    public function sortByName(Request $request)
    {
        $sampah = Sampah::orderBy('nama','desc')->paginate(10);

        return view('home', [
            'sampah' => $sampah
        ]);
    }
    
}

resources/views/home.blade.php
@extends('layouts.main')

@section('content')
    <!-- MAIN CONTENT -->
        <div class="main-content">
          <div class="panel">
            <div class="panel-heading">
              <h3 class="panel-title">SAMPAH</h3>
            </div>
          </div>
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-10">
						<h3 class="panel-title">Semua Sampah</h3>
					</div>
					<div class="col-lg-2">
						<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
							<i class="lnr lnr-plus-circle"></i> Tambah</button>
					</div>
				</div>
				<br>
				<div class="panel">
					<table class="table">
						<thead style="background-color:#E2E2E2">
							<tr>
								<th style="color: black">#</th>
								<th>
									@sortablelink('nama')
									<img src="{{ url('images/Vector (1).png') }}" alt="" srcset="">
								</th>
								<th>
									@sortablelink('kategori','Jenis Sampah')
									<img src="{{ url('images/Vector (1).png') }}" alt="" srcset="">
								</th>
								<th style="color: black">Aksi</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td></td>
								<td>
									<form action="{{ route('sampah.index') }}" method="get">
										@csrf
										<input class="form-control" type="text" name="carinama" id="" placeholder="cari" style="width: 160px;">
									</form>
								</td>
								<td>
									<form action="{{ route('sampah.index') }}" method="get">
										@csrf
										<input class="form-control" type="text" name="carikategori" id="" placeholder="cari" style="width: 160px;">
									</form>
								</td>
								<td></td>
                            </tr>
                            @foreach ($sampah as $item)
							<tr>
								<td>{{ $loop->iteration }}</td>
								<td>{{ $item->nama }}</td>
								<td>{{ $item->kategori }}</td>
								<td>
                                    <form action="{{ route('sampah.destroy',$item->id) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-link btn-xs" style="color: red">
                                            Hapus
                                        </button>
                                    </form>
                                </td>
							</tr>
                            @endforeach
						</tbody>
					</table>
				</div>
				<div class="panel" style="height: 80px;">
					<div class="panel-heading">
						<div class="row">
							<div class="col-lg-9">
								<p>Menampilkan {{ $sampah->count() }} dari {{ $sampah->total() }}</p>
							</div>
							<div class="col-lg-3">
								{{ $sampah->links() }}
							</div>
						</div>
					</div>
				</div>
			</div>
        </div>
@endsection

resources/views/includes/navbar.blade.php
<!-- NAVBAR -->
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="brand" style="background-color: #30aee4; width: 260px;">
          <a href="{{ route('sampah.index') }}"
            ><img
              src="{{ url('images/logow4c.png') }}"
              alt="w4c"
              class="img-responsive logo center-block"
          /></a>
        </div>
        <div class="container-fluid">
          <div class="navbar-btn">
            <button type="button" class="btn-toggle-fullwidth">
              <img src="{{ url('images/Vector.png') }}" alt="" />
            </button>
          </div>
        </div>
      </nav>
      <!-- END NAVBAR -->

resources/views/includes/script.blade.php
<!-- Javascript -->
    <script src="{{ asset('assets/vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <script src="{{ asset('assets/scripts/klorofil-common.js') }}"></script>

resources/views/includes/sidebar.blade.php
<!-- LEFT SIDEBAR -->
      <div id="sidebar-nav" class="sidebar">
        <div class="sidebar-scroll">
          <nav>
            <ul class="nav">
              <li>
                <a href="#subPages" data-toggle="collapse" class="collapsed">
                  <span>Sampah</span>
                  <i class="icon-submenu lnr lnr-chevron-left"></i
                ></a>
                <div id="subPages" class="collapse">
                  <ul class="nav">
                    <li>
                      <a href="{{ route('sampah.index') }}" class=""><i class="fa fa-circle-o"></i> Tambah Sampah</a>
                    </li>
                    <li><a href="{{ route('sampah.index') }}" class=""><i class="fa fa-dot-circle-o"></i> Semua Sampah</a></li>
                  </ul>
                </div>
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <!-- END LEFT SIDEBAR -->

resources/views/includes/style.blade.php
<!-- VENDOR CSS -->
    <link
      rel="stylesheet"
      href="{{ asset('assets/vendor/bootstrap/css/bootstrap.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ asset('assets/vendor/font-awesome/css/font-awesome.min.css') }}"
    />
    <link rel="stylesheet" href="{{ asset('assets/vendor/linearicons/style.css') }}" />
    <link
      rel="stylesheet"
      href="{{ asset('assets/vendor/chartist/css/chartist-custom.css') }}"
    />
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{{ asset('assets/css/main.css') }}" />
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="{{ asset('assets/css/demo.css') }}" />
    <!-- GOOGLE FONTS -->
    <link
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700"
      rel="stylesheet"
    />

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Sistem Manajemen Sampah</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
    />
    @include('includes.style')
  </head>

  <body>
    <!-- WRAPPER -->
    <div id="wrapper">
      
        @include('includes.navbar')
      
        @include('includes.sidebar')
      <!-- MAIN -->
      <div class="main">
        @yield('content')
	</div>

	<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
        <div class="panel">
			<div class="panel-heading">
				<h3 class="panel-title">Tambah Sampah</h3>
			</div>
			<div class="panel-body">
        <form action="{{ route('sampah.store') }}" method="post">
          @csrf
          
          <div class="form-group {{ $errors->has('nama') ? ' has-error' : '' }}">
            <label for="namasampah"><small>Nama Sampah</small></label>
				    <input type="text" class="form-control"  name="nama" value="{{ old('nama') }}" placeholder="Nama Sampah">
            @if ($errors->has('nama'))
              <span class="help-block">{{ $errors->first('nama') }}</span>
            @endif
          </div>
        
          <br>
        
          <div class="form-group {{ $errors->has('kategori') ? ' has-error' : '' }}">
            <label for="kategorisampah"><small>Kategori Sampah</small></label>
				    <select class="form-control" name="kategori">
              <option value="">Kategori Sampah</option>
              <option value="Plastik {{ (old('kategori') == 'Plastik') ? ' selected ' : ''  }}">Plastik</option>
              <option value="Logam {{ (old('kategori') == 'Logam') ? ' selected ' : ''  }}">Logam</option>
              <option value="Kertas {{ (old('kategori') == 'Kertas') ? ' selected ' : ''  }}">Kertas</option>
            </select>
            @if ($errors->has('kategori'))
              <span class="help-block">{{ $errors->first('kategori') }}</span>
            @endif
          </div>
				<br>
				<div class="foot-modal text-right">
					<button type="button" class="btn btn-secondary" style="margin-right:10px" data-dismiss="modal">Close</button>
        	<button type="submit" class="btn btn-primary">Tambah</button>
				</div>
        </form>
			</div>
		</div>
  </div>
</div>
        <!-- END MAIN CONTENT -->
      </div>
      <!-- END MAIN -->
      <div class="clearfix"></div>
     
    </div>
    <!-- END WRAPPER -->
    @include('includes.script')
  </body>
</html>